/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutDocument } from './out-document';


export interface Document { 
    originalFileName?: string;
    randomizedFileName?: string;
    type?: string;
    outDocument?: OutDocument;
}

