/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OcrConfig { 
    language?: string;
    ocrEngineMode?: OcrConfig.OcrEngineModeEnum;
    pageSegmentationMode?: OcrConfig.PageSegmentationModeEnum;
    tessVariables?: { [key: string]: string; };
    preProcessing?: boolean;
    fileFormat?: OcrConfig.FileFormatEnum;
    mergeDocuments?: boolean;
}
export namespace OcrConfig {
    export type OcrEngineModeEnum = 'LEGACY' | 'LSTM' | 'LEGACY_LSTM' | 'DEFAULT';
    export const OcrEngineModeEnum = {
        Legacy: 'LEGACY' as OcrEngineModeEnum,
        Lstm: 'LSTM' as OcrEngineModeEnum,
        LegacyLstm: 'LEGACY_LSTM' as OcrEngineModeEnum,
        Default: 'DEFAULT' as OcrEngineModeEnum
    };
    export type PageSegmentationModeEnum = 'MODE_0' | 'MODE_1' | 'MODE_2' | 'MODE_3' | 'MODE_4' | 'MODE_5' | 'MODE_6' | 'MODE_7' | 'MODE_8' | 'MODE_9' | 'MODE_10' | 'MODE_11' | 'MODE_12' | 'MODE_13';
    export const PageSegmentationModeEnum = {
        _0: 'MODE_0' as PageSegmentationModeEnum,
        _1: 'MODE_1' as PageSegmentationModeEnum,
        _2: 'MODE_2' as PageSegmentationModeEnum,
        _3: 'MODE_3' as PageSegmentationModeEnum,
        _4: 'MODE_4' as PageSegmentationModeEnum,
        _5: 'MODE_5' as PageSegmentationModeEnum,
        _6: 'MODE_6' as PageSegmentationModeEnum,
        _7: 'MODE_7' as PageSegmentationModeEnum,
        _8: 'MODE_8' as PageSegmentationModeEnum,
        _9: 'MODE_9' as PageSegmentationModeEnum,
        _10: 'MODE_10' as PageSegmentationModeEnum,
        _11: 'MODE_11' as PageSegmentationModeEnum,
        _12: 'MODE_12' as PageSegmentationModeEnum,
        _13: 'MODE_13' as PageSegmentationModeEnum
    };
    export type FileFormatEnum = 'PDF' | 'HOCR' | 'TEXT';
    export const FileFormatEnum = {
        Pdf: 'PDF' as FileFormatEnum,
        Hocr: 'HOCR' as FileFormatEnum,
        Text: 'TEXT' as FileFormatEnum
    };
}


