/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchedulerConfigRequest } from './scheduler-config-request';
import { OcrConfigRequest } from './ocr-config-request';


export interface TaskAddRequest { 
    name: string;
    ocrConfig?: OcrConfigRequest;
    schedulerConfig?: SchedulerConfigRequest;
}

